name: release_arm7

on:
  push:
    branches:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'

    - name: run build
      run: GOOS=linux GOARCH=arm GOARM=7 go build .

    - name: zip build
      run: zip shm-et340.zip ./shm-et340

    - name: do release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref_name }} 
        release_name: Release ${{ github.ref_name }}
        body: |
          automatically built by github action
        draft: false
        prerelease: false

    - name: upload binary as release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shm-et340.zip
        asset_name: shm-et340.zip
        asset_content_type: application/zip
